# Reworked for DC kafka from
# https://medium.com/@tetianaokhotnik/docker-compose-for-kafka-single-broker-in-kraft-mode-kafka-ui-and-confluent-rest-proxy-7334da721d4c

version: "3"
services:
  # kafka & kafka_ui -------------------------------------------------------------------------------------
  kafka-1:
    image: ${KAFKA_IMAGE}
    hostname: kafka
    user: ${USER_ID}
    ulimits:
      nofile:
        soft: 102400
        hard: 204800
    ports:
      - ${KAFKA_PORT}:9094
      - 9092:9092
      - 7071:7071
    volumes:
      - ${KAFKA_PATH}:/bitnami/kafka
      - ./prom-jmx:/prom-jmx
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:${KAFKA_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://${CRAWL_HOST_LAN_IP}:${KAFKA_PORT}
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      # ukwa
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_NUM_PARTITIONS=32
      - KAFKA_HEAP_OPTS=-Xmx8g -Xms8g
      - KAFKA_JMX_OPTS=-javaagent:/prom-jmx/jmx_prometheus_javaagent-0.10.jar=7071:/prom-jmx/prom-jmx-agent-config-kafka.yml

  kafka_ui:
    image: ${KAFKA_UI_IMAGE}
    depends_on: 
      - kafka-1
    ports:
      - 9000:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=dc-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - DYNAMIC_CONFIG_ENABLED=true
      - LOGGING_LEVEL_ROOT=warn


  # clamd ------------------------------------------------------------------------------------------------
  clamd:
    image: ${CLAMAV_IMAGE}
    entrypoint: /init-unprivileged
    user: clamav
    volumes:
      - ${CLAMAV_PATH}:/var/lib/clamav
    deploy:
      replicas: 16


  # prometheus -------------------------------------------------------------------------------------------
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    user: ${USER_ID}
    ports:
      - 9191:9090
    volumes:
      - "${PROMETHEUS_CFG_PATH}:/etc/prometheus"
      - "${PROMETHEUS_DATA_PATH}:/prometheus"
    extra_hosts:
      - "hostserver:${CRAWL_HOST_LAN_IP}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1000d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://${CRAWL_HOST_LAN_IP}:9191/'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    networks:
      - default

networks:
  default:
    driver: overlay
    # attachable allows external (outside of docker network) access to outside advertised listener
    attachable: true

